# Site settings
title: Chris Fuller - Tech Blog
email: chris@cjwfuller.com
description: "Tech blog built with Jekyll"
baseurl: ""
url: "http://blog.cjwfuller.com"
twitter_username: cjwfuller
github_username:  cjwfuller
paginate: 10

# Build settings
markdown: kramdown
permalink: pretty

gems:
 - jekyll-redirect-from
 - jekyll-paginate
