# Site settings
title: Chris Fuller
email: chris at cjwfuller dot com
description: "Personal blog built with Jekyll"
baseurl: ""
url: "http://cjwfuller.github.io"
twitter_username: cjwfuller
github_username:  cjwfuller

# Build settings
markdown: kramdown
permalink: pretty
