# Site settings
title: Chris Fuller - Tech Blog
email: chris at cjwfuller dot com
description: "Tech blog built with Jekyll"
baseurl: ""
url: "http://cjwfuller.github.io"
twitter_username: cjwfuller
github_username:  cjwfuller

# Build settings
markdown: kramdown
permalink: pretty
