# Site settings
title: Chris Fuller - Tech Blog
email: <a href="mailto:chris@cjwfuller.com">chris@cjwfuller.com</a>
description: Tech blog built with <a href="http://jekyllrb.com/">Jekyll</a>
baseurl: ""
url: "http://blog.cjwfuller.com"
twitter_username: cjwfuller
github_username:  cjwfuller
paginate: 10

# Build settings
markdown: kramdown
permalink: pretty
