# Site settings
title: Chris Fuller - Tech Blog
email: <a href="mailto:chris@cjwfuller.com">chris@cjwfuller.com</a>
description: "Tech blog built with Jekyll"
baseurl: ""
url: "http://cjwfuller.github.io"
twitter_username: cjwfuller
github_username:  cjwfuller

# Build settings
markdown: kramdown
permalink: pretty
